name: docker-shell

version: '3'
services:
  config:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USE_SSG_REMOTE: "false"
      SETUP_TERMINAL: "false"
    volumes:
      - ./:/tmp/workspace
